# This file was generated by GoReleaser. DO NOT EDIT.
cask "fresh" do
  name "fresh"
  desc "A CLI tool for interactively managing the status of multiple Git repositories"
  homepage "https://github.com/jsmenzies/fresh"
  version "1.9.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fresh"

  on_macos do
    on_intel do
      url "https://github.com/jsmenzies/fresh/releases/download/v#{version}/fresh_#{version}_darwin_amd64.tar.gz"
      sha256 "bbc31e5818c5e9e9cf6a031fb32d7308ab6e27b91130e88994e3a02ada2af558"
    end
    on_arm do
      url "https://github.com/jsmenzies/fresh/releases/download/v#{version}/fresh_#{version}_darwin_arm64.tar.gz"
      sha256 "83b9ec56c4837d2430494cacb346045e385cd82b648556aa207d18aee799c341"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jsmenzies/fresh/releases/download/v#{version}/fresh_#{version}_linux_amd64.tar.gz"
      sha256 "2aa98075d3b78b7a0e31da7471885765ad546017fef2eedd49361c17b883e45c"
    end
    on_arm do
      url "https://github.com/jsmenzies/fresh/releases/download/v#{version}/fresh_#{version}_linux_arm64.tar.gz"
      sha256 "b44946f69649ab03d5adcf13c15656047073e475866a12f3b35986fdbdda668d"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fresh"]
    end
  end

  # No zap stanza required
end
