# This file was generated by GoReleaser. DO NOT EDIT.
cask "fresh" do
  name "fresh"
  desc "A CLI tool for interactively managing the status of multiple Git repositories"
  homepage "https://github.com/jsmenzies/fresh"
  version "1.11.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fresh"

  on_macos do
    on_intel do
      url "https://github.com/jsmenzies/fresh/releases/download/v#{version}/fresh_#{version}_darwin_amd64.tar.gz"
      sha256 "019cba07617238a61d7f581613f7ee713b49685d13611ee27560a40570ef1fb0"
    end
    on_arm do
      url "https://github.com/jsmenzies/fresh/releases/download/v#{version}/fresh_#{version}_darwin_arm64.tar.gz"
      sha256 "4e951d5bec2bafd46645ae0e3b66d6519f43c94da6b94f61e3bb1151dd5f6f78"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jsmenzies/fresh/releases/download/v#{version}/fresh_#{version}_linux_amd64.tar.gz"
      sha256 "1334b7f24efa5be73377d29461a1566ea2e844dcd4b2e9e45327dc1063de3c1c"
    end
    on_arm do
      url "https://github.com/jsmenzies/fresh/releases/download/v#{version}/fresh_#{version}_linux_arm64.tar.gz"
      sha256 "084659bc4a333ac4b5fd99b20499f51756d25f72a86794891251b3afb11f569d"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fresh"]
    end
  end

  # No zap stanza required
end
