# This file was generated by GoReleaser. DO NOT EDIT.
cask "fresh" do
  name "fresh"
  desc "A CLI tool for interactively managing the status of multiple Git repositories"
  homepage "https://github.com/jsmenzies/fresh"
  version "1.9.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fresh"

  on_macos do
    on_intel do
      url "https://github.com/jsmenzies/fresh/releases/download/v#{version}/fresh_#{version}_darwin_amd64.tar.gz"
      sha256 "e8a69e5acd5cd1a8587e9aea8572f6bdf30fd7d063e227beaf30739498f3f80d"
    end
    on_arm do
      url "https://github.com/jsmenzies/fresh/releases/download/v#{version}/fresh_#{version}_darwin_arm64.tar.gz"
      sha256 "bd0b5c82b2ebce3788788b0ea9ce86510a08a0722e212ccaafc979481b980318"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jsmenzies/fresh/releases/download/v#{version}/fresh_#{version}_linux_amd64.tar.gz"
      sha256 "a39206accdfbe0e8da40956b7349dc8cb09b9859b8a7d62301ca2adefdf25d98"
    end
    on_arm do
      url "https://github.com/jsmenzies/fresh/releases/download/v#{version}/fresh_#{version}_linux_arm64.tar.gz"
      sha256 "3edf98c819111667b35d87a8ccee9dfc86850fead6a86aa0a571b0c3b70a9e33"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fresh"]
    end
  end

  # No zap stanza required
end
