# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Autocommit < Formula
  desc "AI-powered git commit message generator"
  homepage "https://github.com/jsmenzies/autocommit"
  version "1.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jsmenzies/autocommit/releases/download/v1.2.0/autocommit_1.2.0_darwin_amd64.tar.gz"
      sha256 "ccd54ebbe55efe5c811392a7d931d4add2c57c72b3804768052e145cbb94a492"

      def install
        bin.install "autocommit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jsmenzies/autocommit/releases/download/v1.2.0/autocommit_1.2.0_darwin_arm64.tar.gz"
      sha256 "7f7d4ed0f82d91d1d1fb158098775ae4279476db2ab04df4de1e7cc451b64fe5"

      def install
        bin.install "autocommit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jsmenzies/autocommit/releases/download/v1.2.0/autocommit_1.2.0_linux_amd64.tar.gz"
      sha256 "c4cba5f93628561580c52b22888b668410b8ec51dc2ac29d32bbc1b7d2f7fbc4"
      def install
        bin.install "autocommit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jsmenzies/autocommit/releases/download/v1.2.0/autocommit_1.2.0_linux_arm64.tar.gz"
      sha256 "45b472c9f5116fdffa8d51f8fd5c03d5ef546cf67fdd850b9fd685663738c6ab"
      def install
        bin.install "autocommit"
      end
    end
  end
end
