# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Autocommit < Formula
  desc "AI-powered git commit message generator"
  homepage "https://github.com/jsmenzies/autocommit"
  version "3.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jsmenzies/autocommit/releases/download/v3.2.2/autocommit-macos-arm64"
      sha256 "bc7e638098aab5f3ca1a6ee871f5abd782e95da2d992ee6b130e9b3dcc2b1a7a"

      def install
        bin.install "autocommit-macos-arm64" => "autocommit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jsmenzies/autocommit/releases/download/v3.2.2/autocommit-macos-arm64"
      sha256 "bc7e638098aab5f3ca1a6ee871f5abd782e95da2d992ee6b130e9b3dcc2b1a7a"

      def install
        bin.install "autocommit-macos-arm64" => "autocommit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jsmenzies/autocommit/releases/download/v3.2.2/autocommit-macos-arm64"
      sha256 "bc7e638098aab5f3ca1a6ee871f5abd782e95da2d992ee6b130e9b3dcc2b1a7a"
      def install
        bin.install "autocommit-macos-arm64" => "autocommit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jsmenzies/autocommit/releases/download/v3.2.2/autocommit-macos-arm64"
      sha256 "bc7e638098aab5f3ca1a6ee871f5abd782e95da2d992ee6b130e9b3dcc2b1a7a"
      def install
        bin.install "autocommit-macos-arm64" => "autocommit"
      end
    end
  end
end
